### ISSUE TITLE
2017.1: Display of publish settings reset to default on each open of that panel

### ISSUE THREAD

**Issue by ericente** [pixijs/pixi-animate-extension#38]
Since upgrading to Adobe Animate 2017.1, every time the Publish Settings panel is open, the values it displays are the defaults for a new document. Using the Output File filepicker to select an output location seems to restore the previous properties (except for the Output File field which is set to the new value).

**Comment by bigtimebuddy** [comment]
I am looking into this.

I suspect it has something to do with this line: https://github.com/jiborobot/pixi-animate-extension/blob/master/src/extension/dialog/index.js#L297 which is responsible for getting the initial state and settings from Animate.

There might be a newer way to support this or Adobe might have renamed the event to `animate` instead of `flash`. It's hard to tell because Adobe's docs for CEP extensions are horrible.

**Comment by bigtimebuddy** [comment]
Found a workaround by getting the publish settings via JSFL. Seems to work fine.

**Comment by stevenalanstark** [comment]
Please re-open this issue.

I believe it's a Windows issue having to do with escaping \'s and converting to JSON and back. 


To re-produce the issue, save out the the file and open publish settings. Right now we can close and re-open them just fine.

change the output file to a completely different folder from the .FLA

Save, re-open publish settings. 

When re-opening, it can't find the output file, and there is an if statement that will reset the publish settings to their default state if this is not found. 

I think it's all about the windows file directories needing to be escaped, and I am looking into this myself. I will update this issue with any findings.

**Comment by stevenalanstark** [comment]
Please re-open this issue.

I believe it's a Windows issue having to do with escaping \'s and converting to JSON and back. 


To re-produce the issue, save out the the file and open publish settings. Right now we can close and re-open them just fine.

change the output file to a completely different folder from the .FLA

Save, re-open publish settings. 

When re-opening, it can't find the output file, and there is an if statement that will reset the publish settings to their default state if this is not found. 

I think it's all about the windows file directories needing to be escaped, and I am looking into this myself. I will update this issue with any findings.

**Comment by ericente** [comment]
Should be fixed in 1.4.0
