### ISSUE TITLE
Frame script are not export

### ISSUE THREAD

**Issue by k8w** [pixijs/pixi-animate-extension#50]
**Problem**
If a MovieClip only have 1 frame, its frame script would never be exported.
(Actually it is exported to the output `json` file, but not to the output `js` file.

**Reproduction**
1. Make a new MovieClip
1. Only 1 frame, and add script at frame0, for example:
```
console.log('test');
```
3. Publish and run , and you would not see `test` in the console.

[Demo project](https://www.dropbox.com/s/4fp4q0yxtxr12r3/test.zip?dl=0)

**Comment by ericente** [comment]
fixed in 1.4.0
