### ISSUE TITLE
Filters for movieclips

### ISSUE THREAD

**Issue by herrKlein** [pixijs/pixi-animate-extension#61]
Hi, I would really love to use the animate extension but I can't use filters.

I understand that pixiJS doesn't know how to handle/render them. But I was hoping to add filter effects in animateCC when drawing my assets and use the whole movieclip as a bitmap on pixi export, using Display -> Render -> Export as bitmap. 

Is it possible to switch filters on in the settings so I can use them at least for my bitmap exported movieclips ?

**Comment by ericente** [comment]
This should now be possible in v1.4.1. Also, see this JSFL script for easy toggling between bitmap and original versions: https://github.com/SpringRoll/FlashToolkit/blob/master/src/Commands/Utilities/Copy%20Layers%20To%20Bitmap.jsfl
