### ISSUE TITLE
Synced MovieClips(Graphics) are not exported correctly in Animate 2019

### ISSUE THREAD

**Issue by Ch1pStar** [pixijs/pixi-animate-extension#69]
After some digging, I found that in Animate 2019 synced movie clip(graphic) instances are exported with type 
`"type" : "movieclip"`, instead of `"type" : "graphic"` in the JSON temp file, which causes them to be exported as regular movie clips in the output js code.
Furthermore in the method `TimelineWriter::Finish(FCM::U_Int32 resId, FCM::StringRep16 pName, std::string name)`, the 3rd argument(name) is given as 'Graphic<1,2,3>' in Animate 2018, where in 2019 it is the library name of the symbol, so the logic that determines the type of the timeline fails. I imagine this is where a fix could be applied, but would like to hear some input how to go about it exactly.

Edit: After some more digging, I found the origin point of the name to be `ResourcePalette::AddSymbol(...)`. Note that even the documentation states that for graphic instances the name should be NULL, but in Animate 2019 the `pName` argument has a string value for graphic instances.
Here is a snippet from the declaration of the function.
```
/**  
 * @brief  This function is invoked to add a symbol to the resource palette.
 *
 * @param  resourceId (IN)
 *         Resource Id associated with the symbol which is getting 
 *         added to the palette.
 *
 * @param  pName (IN)
 *         Name of the symbol which is getting added to the palette. For graphic
 *         symbols, pName can be NULL.
 *
 * @param  pTimelineBuilder (IN)
 *         TimelineBuilder object for the symbol. Contains all the timeline commands.
 *
 * @return On success, FCM_SUCCESS is returned, else an error code is returned.
 */
virtual FCM::Result _FCMCALL AddSymbol(
    FCM::U_Int32 resourceId, 
    FCM::StringRep16 pName, 
    Exporter::Service::PITimelineBuilder pTimelineBuilder) = 0;

```

**Comment by ericente** [comment]
Fixed in v1.4.1
