### ISSUE TITLE
Stage with empty MovieClip is not exported

### ISSUE THREAD

**Issue by MaksymDehtiarenko** [pixijs/pixi-animate-extension#70]
Windows 10, AnimateCC v19.2.1, PixiAnimate v1.4.0, Electron@6.0.0.

All worked well with Electron@1.6.1. 
After updating AnimateCC to last version it asks to use Electron v1.8.2 or greater. I updated Electron and there was a problem with publishing PixiAnimate document from .fla to .js. 
No .js file is created, only .json with resources, similar to what has already been described in other issues. Electron throws the error "cannot read property 'scripts' of undefined". Tried with Electron@1.8.8 and Electron@6.0.0.

Empirically I found that this happens when I have an empty MovieClip somewhere on the stage. If I remove it from the stage or draw something inside it, all published well with .js file and others.
So, steps to reproduce - just add empty MovieClip on the stage and try to publish. In "PixiAnimate Publish Settings" I exported only "Images/".

**Comment by ericente** [comment]
Thanks for the report - AFAIK, this issue is not new. I have a fix for this issue already merged to the `master` branch and will be included in the next release of the plugin. If you have a need to use empty MovieClips in the meantime, you can build this repo and install the created ZXP.

**Comment by bigtimebuddy** [comment]
@ericente should we make a release v1.4.1? seems like a big enough crash

**Comment by MrPigsel** [comment]
Now, I have the same problem! Any ideas, to solve now?

**Comment by ericente** [comment]
Fixed in v1.4.1
