### ISSUE TITLE
Publish not generating .js file

### ISSUE THREAD

**Issue by carlosdr-ntd** [pixijs/pixi-animate-extension#73]
Hi,

We have:

- Mac OS catalina 10.15.1
- node 8.16.1
- electron 1.4.13 -> which electron: /Users/name/.nvm/versions/node/v8.16.1/bin/electron
- Adobe Animate CC 2019 version 19.1

We tried: `ln -s /Users/name/.nvm/versions/node/v8.16.1/bin/electron /usr/local/bin/electron`

When we try to publish the pixi with the lib options checked, Adobe gets stuck. If we don't select, it we don't have the .js file, but we have a .html and .json.

Please help.

**Comment by idiazpor-ntd** [comment]
@bigtimebuddy please help! 😢

**Comment by idiazpor-ntd** [comment]
You should replace the electron folder from /usr/local/bin/electron with the one in /Users/name/.nvm/versions/node/v8.16.1/bin/electron.
So, try: ```rm -rf /usr/local/bin/electron``` and make again the ```ln -s [...]``` command.

**Comment by carlosdr-ntd** [comment]
It works, thank you!
