### ISSUE TITLE
adobe animate will be stuck when publish，if export as Sprites Sheets is checked

### ISSUE THREAD

**Issue by koolou** [pixijs/pixi-animate-extension#81]
![image](https://user-images.githubusercontent.com/349998/118345588-1cd6d680-b568-11eb-8da5-db2b6b02d230.png)
When i try to publish, adobe animate cc will be stuck, if export as Sprites Sheets is checked.
If I leave this option unchecked， the export goes smoothly.
Has anyone encountered this problem? know how to solve this situation?
My environment is： animate cc 2019，electron v12.0.5， Node v14.16
Here is the test file.
[test.fla.zip](https://github.com/pixijs/pixi-animate-extension/files/6481776/test.fla.zip)

**Comment by koolou** [comment]
npm -g uninstall electron
npm -g install electron@1.8.2

**Comment by andrewstart** [comment]
This should be fixed in the next release - Electron 12 had a breaking change but any earlier version should be fine.
